on:
  push:

jobs:
  check:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Run tests
      id: test
      run: |
        deno test
